spring:

  application:
    name: jobpilot-ai

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: jobpilot-ai-ingestion
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.jobpilot.ai.messaging.event.DocumentUploadedEvent

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}


jobpilot:
  base-url: http://localhost:8080


server:
  port: 8081