spring.application.name=JobPilot

# MongoDB
spring.mongodb.uri=mongodb://JobPilot:JobPilot@localhost:27017/JobPilot?authSource=admin

# Web
spring.web.resources.cache.period=0

# Server
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging
logging.level.root=INFO
logging.level.com.jobpilot=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.security=INFO