spring:

  application:
    name: JobPilot

  # =========================================================
  # MONGODB
  # =========================================================
  data:
    mongodb:
      uri: mongodb://JobPilot:JobPilot@localhost:27017/JobPilot?authSource=admin

  # =========================================================
  # WEB
  # =========================================================
  web:
    resources:
      cache:
        period: 0

# =========================================================
# SERVER
# =========================================================

server:
  port: 8080

# =========================================================
# ACTUATOR
# =========================================================

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

# =========================================================
# LOGGING
# =========================================================

logging:
  level:
    root: INFO
    com.jobpilot: DEBUG

    # MongoDB queries
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

    # Spring Security - useful during local development
    org.springframework.security: INFO